apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: kustomize
spec:
  params:
    - name: imagestream
      type: string
      description: The image to update the deployment with
    - name: overlaypath
      type: string
      description: path to the overlay directory
  steps:
    - name: kustomzie
      workingDir: $(workspaces.source.path)
      image: quay.io/redhatworkshops/kustomize-task:v4.0.5
      script: |
        #!/usr/bin/env /bin/sh
        echo "Running: kustomize edit set image $(params.imagestream)"
        cd $(params.overlaypath)
        kustomize edit set image $(params.imagestream)
  workspaces:
    - name: source