apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rest-heroes-db-config-secret.yaml
  - rest-heroes-db-deploy.yaml
  - rest-heroes-db-init-cm.yaml
  - est-heroes-db-service.yaml
