kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    gitops.ownedBy: openshift-gitops
  name: apicurio-registry-operator
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: cluster-services
  source:
    path: 01-cluster-admin/03-cluster-services/apicurio-registry-operator
    repoURL: https://github.com/pittar-demos/rosa-devops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy