apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superhero-battle-cicd

bases:
  - ../../../base/cicd/node-pipeline

patches:
  - target:
      group: ''
      version: v1
      kind: PersistentVolumeClaim
      name: node-workspace
    patch: |-
      - op: replace
        path: /metadata/name
        value: battle-ui-workspace
  - target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      name: node-pipeline
    patch: |-
      - op: replace
        path: /metadata/name
        value: battle-ui-pipeline
  - target:
      group: tekton.dev
      version: v1beta1
      kind: PipelineRun
      name: initial-run
    patch: |-
      - op: replace
        path: /metadata/name
        value: battle-ui-pipeline-initial-run
      - op: replace
        path: /spec/pipelineRef/name
        value: battle-ui-pipeline
      - op: add
        path: /spec/params/-
        value:
          name: app-name
          value: battle-ui
      - op: add
        path: /spec/params/-
        value:
          name: git-url
          value: http://gitea.scm.svc.cluster.local:3000/developer/battle-ui.git
      - op: add
        path: /spec/workspaces/-
        value:
          name: shared-workspace
          persistentVolumeClaim:
            claimName: battle-ui-workspace
