kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../../02-tenants/superhero-battle/cicd
  #- ../../../02-tenants/superhero-battle/dev
  #- ../../../02-tenants/superhero-battle/test

resources:
  - tenants-project.yaml
